### ISSUE TITLE
 'maximum template recursion' error after a few hours

### ISSUE THREAD

**Issue by agoyaliitk** [bwbaugh/wikipedia-extractor#7] opened 2015-04-09 21:02 UTC
I am running a python script on English Wikipedia xml dump file to extract text for the Wikipedia articles. I am doing everything as told. It seems a fairly straightforward task.

The script runs fine till some time and extracts some articles. But after a few hours, it starts giving this error 'Maximum template recursion'. I don't understand why.

**Comment by bwbaugh** [comment] 2015-04-09 21:32
Sounds like a duplicate of #6. Trying checking out the previous version / commit.

As soon as the authors upload a fix to the official website, this mirror repo will be updated.

**Closed as completed by bwbaugh** 2015-04-09 21:32 UTC
